import {
  AppUser,
  TechnicianProfile,
  ServiceCategory,
  Booking,
  Review,
  ChatConversation,
  AppNotification,
  Complaint,
  Offer,
} from '../types';

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'user_cust_1',
    name: 'أحمد بن عبد الرحمن المنصوري',
    phone: '0551234567',
    email: 'ahmed.mansoori@example.com',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    city: 'الرياض',
    district: 'حي الملقا',
    address: 'شارع أنس بن مالك، فيلا 42',
    location: {
      lat: 24.774265,
      lng: 46.638496,
      city: 'الرياض',
      district: 'حي الملقا',
      addressText: 'شارع أنس بن مالك، حي الملقا',
    },
    status: 'active',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'user_cust_2',
    name: 'سارة خالد الدوسري',
    phone: '0509876543',
    email: 'sara.d@example.com',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    city: 'جدة',
    district: 'حي الروضة',
    address: 'شارع الأمير سلطان',
    location: {
      lat: 21.5794,
      lng: 39.1607,
      city: 'جدة',
      district: 'حي الروضة',
      addressText: 'شارع الأمير سلطان، الروضة',
    },
    status: 'active',
    createdAt: '2025-02-01T12:00:00Z',
  },
  {
    id: 'user_tech_1',
    name: 'م. طارق الخالدي',
    phone: '0562233445',
    email: 'tariq.tech@khadamati.com',
    role: 'technician',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    city: 'الرياض',
    district: 'حي النرجس',
    address: 'طريق الملك سلمان',
    location: {
      lat: 24.8142,
      lng: 46.6582,
      city: 'الرياض',
      district: 'حي النرجس',
      addressText: 'طريق الملك سلمان، النرجس',
    },
    status: 'active',
    createdAt: '2024-11-15T08:00:00Z',
  },
  {
    id: 'user_tech_2',
    name: 'أبو فهد - فني سباكة معتمد',
    phone: '0543344556',
    email: 'fahad.plumbing@khadamati.com',
    role: 'technician',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    city: 'الرياض',
    district: 'حي الصحافة',
    address: 'شارع العليا',
    location: {
      lat: 24.792,
      lng: 46.65,
      city: 'الرياض',
      district: 'حي الصحافة',
      addressText: 'شارع العليا، حي الصحافة',
    },
    status: 'active',
    createdAt: '2024-10-20T09:30:00Z',
  },
  {
    id: 'user_tech_3',
    name: 'م. سامر النجار - تكييف وتبريد',
    phone: '0558877665',
    email: 'samer.ac@khadamati.com',
    role: 'technician',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    city: 'جدة',
    district: 'حي الزهراء',
    address: 'شارع صاري',
    location: {
      lat: 21.584,
      lng: 39.141,
      city: 'جدة',
      district: 'حي الزهراء',
      addressText: 'شارع صاري، حي الزهراء',
    },
    status: 'active',
    createdAt: '2024-12-05T14:00:00Z',
  },
  {
    id: 'user_tech_4',
    name: 'حسام العمري - كهربائي منازل',
    phone: '0567788990',
    email: 'hussam.electric@khadamati.com',
    role: 'technician',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    city: 'الدمام',
    district: 'حي الشاطئ',
    address: 'طريق الخليج',
    location: {
      lat: 26.434,
      lng: 50.103,
      city: 'الدمام',
      district: 'حي الشاطئ',
      addressText: 'طريق الخليج، حي الشاطئ',
    },
    status: 'active',
    createdAt: '2025-01-05T11:00:00Z',
  },
  {
    id: 'user_admin_1',
    name: 'إدارة خدمتي - وليد الحداد',
    phone: '0599999999',
    email: 'admin@khadamati.app',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
    city: 'الرياض',
    district: 'حي السليمانية',
    address: 'برج خدمتي الرقمي',
    location: {
      lat: 24.7136,
      lng: 46.6753,
      city: 'الرياض',
      district: 'حي السليمانية',
      addressText: 'برج خدمتي الرقمي',
    },
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const INITIAL_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat_electric',
    nameAr: 'كهرباء وإنارة',
    nameEn: 'Electricity & Lighting',
    iconName: 'Zap',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&auto=format&fit=crop&q=80',
    description: 'صيانة وتمديد الكهرباء، لوحات القواطع، تأسيس إنارة LED وثريات، وتصليح الأعطال الطارئة.',
    isPopular: true,
    techniciansCount: 38,
    startingPrice: 80,
    color: 'from-amber-500 to-orange-500',
  },
  {
    id: 'cat_plumbing',
    nameAr: 'سباكة وصحية',
    nameEn: 'Plumbing & Sanitation',
    iconName: 'Wrench',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=500&auto=format&fit=crop&q=80',
    description: 'كشف وإصلاح تسريبات المياه، صيانة الخلاطات، تمديد وتصليح شبكات الصرف والغطاسات والخزانات.',
    isPopular: true,
    techniciansCount: 45,
    startingPrice: 90,
    color: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'cat_ac',
    nameAr: 'تكييف وتبريد',
    nameEn: 'AC & Cooling',
    iconName: 'Wind',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&auto=format&fit=crop&q=80',
    description: 'غسيل وصيانة مكيفات سبليت وشباك ومركزي، تعبئة فريون أصلي، وفحص كمبروسر التسريب.',
    isPopular: true,
    techniciansCount: 52,
    startingPrice: 120,
    color: 'from-teal-500 to-emerald-600',
  },
  {
    id: 'cat_carpentry',
    nameAr: 'نجارة وأثاث',
    nameEn: 'Carpentry & Woodwork',
    iconName: 'Hammer',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&auto=format&fit=crop&q=80',
    description: 'تركيب وصيانة غرف النوم والمطابخ، تفصيل أبواب وخزائن، وتعديل مقابض وكوالين الأبواب.',
    isPopular: false,
    techniciansCount: 29,
    startingPrice: 100,
    color: 'from-yellow-600 to-amber-800',
  },
  {
    id: 'cat_paint',
    nameAr: 'دهانات وديكور',
    nameEn: 'Painting & Decor',
    iconName: 'Paintbrush',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&auto=format&fit=crop&q=80',
    description: 'دهان جدران داخلي وخارجي، تركيب ورق جدران، معالجة الرطوبة والتشققات وتركيب الفوم والبدائل.',
    isPopular: false,
    techniciansCount: 22,
    startingPrice: 150,
    color: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'cat_cleaning',
    nameAr: 'تنظيف وتعقيم',
    nameEn: 'Cleaning & Hygiene',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500&auto=format&fit=crop&q=80',
    description: 'تنظيف عميق للمنازل والفلل، غسيل كنب وسجاد بالبخار، جلي رخام وبلاط، وتعقيم شامل.',
    isPopular: true,
    techniciansCount: 60,
    startingPrice: 180,
    color: 'from-emerald-500 to-teal-700',
  },
  {
    id: 'cat_appliances',
    nameAr: 'صيانة أجهزة منزلية',
    nameEn: 'Home Appliances',
    iconName: 'Cpu',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&auto=format&fit=crop&q=80',
    description: 'صيانة غسالات أوتوماتيك، ثلاجات، أفران غاز وكهرباء، ميكروويف، وتوفير قطع غيار أصلية مع الضمان.',
    isPopular: true,
    techniciansCount: 34,
    startingPrice: 110,
    color: 'from-rose-500 to-pink-600',
  },
  {
    id: 'cat_electronics',
    nameAr: 'صيانة جوالات وإلكترونيات',
    nameEn: 'Electronics & Mobiles',
    iconName: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=500&auto=format&fit=crop&q=80',
    description: 'صيانة شاشات وبطاريات الجوالات المنزلية، صيانة اللابتوبات، وتركيب كاميرات المراقبة والشبكات.',
    isPopular: false,
    techniciansCount: 19,
    startingPrice: 70,
    color: 'from-violet-500 to-purple-700',
  },
  {
    id: 'cat_moving',
    nameAr: 'نقل وتركيب عفش',
    nameEn: 'Furniture Moving',
    iconName: 'Truck',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&auto=format&fit=crop&q=80',
    description: 'نقل عفش مع الفك والتركيب والتغليف المحكم، أسطول شاحنات مجهزة وفريق عمالة محترف.',
    isPopular: false,
    techniciansCount: 25,
    startingPrice: 350,
    color: 'from-sky-600 to-blue-800',
  },
  {
    id: 'cat_car',
    nameAr: 'صيانة سيارات متنقلة',
    nameEn: 'Mobile Auto Service',
    iconName: 'Car',
    image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=500&auto=format&fit=crop&q=80',
    description: 'تبديل بطاريات وإطارات عند المنزل، فحص كمبيوتر فوري، وتغيير زيت وفلاتر بجودة عالية.',
    isPopular: true,
    techniciansCount: 28,
    startingPrice: 130,
    color: 'from-red-500 to-rose-700',
  },
  {
    id: 'cat_gardening',
    nameAr: 'حدائق ومسابح',
    nameEn: 'Gardens & Pools',
    iconName: 'Trees',
    image: 'https://images.unsplash.com/photo-1558904541-efa8c4a08931?w=500&auto=format&fit=crop&q=80',
    description: 'تنسيق حدائق وقص أشجار، شبكات ري ذكية، صيانة فلاتر مسابح وكلورة وتنظيف كيميائي معتمد.',
    isPopular: false,
    techniciansCount: 16,
    startingPrice: 200,
    color: 'from-green-600 to-emerald-800',
  },
  {
    id: 'cat_pest',
    nameAr: 'مكافحة حشرات وعزل',
    nameEn: 'Pest Control & Insulation',
    iconName: 'ShieldCheck',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=500&auto=format&fit=crop&q=80',
    description: 'رش مبيدات آمنة وبدون رائحة مع الضمان، عزل أسطح وخزانات مائية ضد التسريب والحرارة.',
    isPopular: false,
    techniciansCount: 20,
    startingPrice: 160,
    color: 'from-slate-600 to-slate-800',
  },
];

export const INITIAL_TECHNICIANS: TechnicianProfile[] = [
  {
    id: 'user_tech_1',
    name: 'م. طارق الخالدي',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    phone: '0562233445',
    email: 'tariq.tech@khadamati.com',
    city: 'الرياض',
    district: 'شمال الرياض - حي النرجس والملقا',
    specialtyId: 'cat_electric',
    specialtyName: 'كهرباء وإنارة',
    services: [
      { id: 's1', name: 'فحص وإصلاح شورت كهربائي', price: 120, unit: 'زيارة + كشف', description: 'كشف دقيق بالأجهزة وإصلاح القواطع المترددة' },
      { id: 's2', name: 'تأسيس وتركيب ثريات وإضاءة LED', price: 70, unit: 'لكل نقطة', description: 'تثبيت آمن ومحترف مع موازنة الأحمال' },
      { id: 's3', name: 'صيانة وتغيير لوحة القواطع الرئيسية', price: 250, unit: 'لوحة كاملة', description: 'تحديث القواطع إلى شنايدر أو ABB' },
      { id: 's4', name: 'تمديد أسلاك وتوصيل مفاتيح إضافية', price: 90, unit: 'للغرفة' },
    ],
    experienceYears: 8,
    bio: 'مهندس كهربائي معتمد، خبرة 8 سنوات في صيانة منازل الفلل والقصور بالرياض. دقة في المواعيد واستخدام قطع غيار أصلية ومطابقة للمواصفات السعودية SASO.',
    basePrice: 100,
    workingHours: '8:00 ص - 10:00 م (طوال الأسبوع)',
    location: {
      lat: 24.8142,
      lng: 46.6582,
      city: 'الرياض',
      district: 'حي النرجس',
      addressText: 'طريق الملك سلمان، النرجس',
    },
    isAvailable: true,
    rating: 4.9,
    reviewsCount: 142,
    completedOrders: 310,
    portfolioImages: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=500&auto=format&fit=crop&q=80',
    ],
    verificationStatus: 'verified',
    identityNumber: '1098765432',
  },
  {
    id: 'user_tech_2',
    name: 'أبو فهد - فني سباكة معتمد',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    phone: '0543344556',
    email: 'fahad.plumbing@khadamati.com',
    city: 'الرياض',
    district: 'وسط وشمال الرياض - حي الصحافة والياسمين',
    specialtyId: 'cat_plumbing',
    specialtyName: 'سباكة وصحية',
    services: [
      { id: 's21', name: 'كشف تسربات المياه إلكترونياً بدون تكسير', price: 180, unit: 'فحص شامل', description: 'تقرير معتمد بجهاز النيتروجين والموجات' },
      { id: 's22', name: 'صيانة وتركيب خلاطات ومغاسل وشاور', price: 80, unit: 'لكل قطعة' },
      { id: 's23', name: 'تسليك مجاري بالضغط والنيتروجين', price: 150, unit: 'للخط' },
      { id: 's24', name: 'صيانة دينمو وغطاس الخزان وتغيير العوامة', price: 160, unit: 'جهاز' },
    ],
    experienceYears: 12,
    bio: 'فني سباكة متخصص ومحترف منذ 12 عاماً. خدمة سريعة لحالات الطوارئ وتسريب المياه، تركيب أدوات صحية إيطالية وألمانية بضمان على العمل.',
    basePrice: 90,
    workingHours: '24 ساعة لحالات الطوارئ',
    location: {
      lat: 24.792,
      lng: 46.65,
      city: 'الرياض',
      district: 'حي الصحافة',
      addressText: 'شارع العليا، حي الصحافة',
    },
    isAvailable: true,
    rating: 4.8,
    reviewsCount: 198,
    completedOrders: 480,
    portfolioImages: [
      'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=500&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=500&auto=format&fit=crop&q=80',
    ],
    verificationStatus: 'verified',
    identityNumber: '1023456789',
  },
  {
    id: 'user_tech_3',
    name: 'م. سامر النجار - تكييف وتبريد',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    phone: '0558877665',
    email: 'samer.ac@khadamati.com',
    city: 'جدة',
    district: 'حي الزهراء والروضة والشاطئ',
    specialtyId: 'cat_ac',
    specialtyName: 'تكييف وتبريد',
    services: [
      { id: 's31', name: 'غسيل وتنظيف مكيف سبليت مع جراب الحماية', price: 99, unit: 'للمكيف', description: 'تنظيف الوحدة الداخلية والخارجية وضغط الماء' },
      { id: 's32', name: 'تعبئة فريون هندي/أمريكي R410 و R22', price: 150, unit: 'للوحدة' },
      { id: 's33', name: 'صيانة صوت الكمبروسر أو تهريب الماء', price: 120, unit: 'فحص + إصلاح' },
      { id: 's34', name: 'فك ونقل وتركيب مكيف سبليت مع نحاس', price: 220, unit: 'للمكيف' },
    ],
    experienceYears: 9,
    bio: 'متخصص في جميع أنواع المكيفات (جري، ال جي، دايكن، ميتسوبيشي، كارير). أضمن تبريد عالي مع توفير استهلاك الطاقة ونظافة مكان العمل 100%.',
    basePrice: 120,
    workingHours: '7:30 ص - 11:00 م',
    location: {
      lat: 21.584,
      lng: 39.141,
      city: 'جدة',
      district: 'حي الزهراء',
      addressText: 'شارع صاري، حي الزهراء',
    },
    isAvailable: true,
    rating: 4.95,
    reviewsCount: 230,
    completedOrders: 560,
    portfolioImages: [
      'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&auto=format&fit=crop&q=80',
    ],
    verificationStatus: 'verified',
    identityNumber: '1088776655',
  },
  {
    id: 'user_tech_4',
    name: 'حسام العمري - كهربائي منازل',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    phone: '0567788990',
    email: 'hussam.electric@khadamati.com',
    city: 'الدمام',
    district: 'حي الشاطئ والفيصلية والخبر',
    specialtyId: 'cat_electric',
    specialtyName: 'كهرباء وإنارة',
    services: [
      { id: 's41', name: 'صيانة طوارئ وانقطاع كهرباء', price: 100, unit: 'زيارة' },
      { id: 's42', name: 'تركيب مراوح شفط وشاشات وإنارة', price: 60, unit: 'قطعة' },
    ],
    experienceYears: 6,
    bio: 'كهربائي منازل في المنطقة الشرقية (الدمام والخبر والظهران). سرعة في الاستجابة وحلول هندسية آمنة.',
    basePrice: 80,
    workingHours: '9:00 ص - 9:00 م',
    location: {
      lat: 26.434,
      lng: 50.103,
      city: 'الدمام',
      district: 'حي الشاطئ',
      addressText: 'طريق الخليج، حي الشاطئ',
    },
    isAvailable: false,
    rating: 4.7,
    reviewsCount: 85,
    completedOrders: 190,
    portfolioImages: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&auto=format&fit=crop&q=80',
    ],
    verificationStatus: 'verified',
    identityNumber: '1077665544',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book_101',
    bookingNumber: 'KD-2025-081',
    customerId: 'user_cust_1',
    customerName: 'أحمد بن عبد الرحمن المنصوري',
    customerPhone: '0551234567',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    technicianId: 'user_tech_1',
    technicianName: 'م. طارق الخالدي',
    technicianPhone: '0562233445',
    technicianAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    specialtyId: 'cat_electric',
    specialtyName: 'كهرباء وإنارة',
    serviceItems: ['فحص وإصلاح شورت كهربائي', 'تأسيس وتركيب ثريات وإضاءة LED'],
    problemDescription: 'يوجد انقطاع متكرر في قاطع الصالة الرئيسية مع وجود رائحة احتراق خفيفة عند تشغيل المكيف والإضاءة معاً.',
    problemImages: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&auto=format&fit=crop&q=80',
    ],
    location: {
      lat: 24.774265,
      lng: 46.638496,
      city: 'الرياض',
      district: 'حي الملقا',
      addressText: 'شارع أنس بن مالك، فيلا 42',
    },
    scheduledDate: '2025-08-20',
    scheduledTime: '04:00 م - 06:00 م',
    notes: 'يرجى الاتصال قبل الوصول بـ 15 دقيقة، البوابة الشمالية.',
    status: 'in_progress',
    paymentMethod: 'card',
    paymentStatus: 'paid',
    totalPrice: 190,
    estimatedPrice: 190,
    createdAt: '2025-08-19T09:15:00Z',
  },
  {
    id: 'book_102',
    bookingNumber: 'KD-2025-079',
    customerId: 'user_cust_1',
    customerName: 'أحمد بن عبد الرحمن المنصوري',
    customerPhone: '0551234567',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    technicianId: 'user_tech_2',
    technicianName: 'أبو فهد - فني سباكة معتمد',
    technicianPhone: '0543344556',
    technicianAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    specialtyId: 'cat_plumbing',
    specialtyName: 'سباكة وصحية',
    serviceItems: ['كشف تسربات المياه إلكترونياً بدون تكسير'],
    problemDescription: 'تهريب مياه خفيف يظهر في سقف الدور الأرضي أسفل الحمام الرئيسي.',
    problemImages: [],
    location: {
      lat: 24.774265,
      lng: 46.638496,
      city: 'الرياض',
      district: 'حي الملقا',
      addressText: 'شارع أنس بن مالك، فيلا 42',
    },
    scheduledDate: '2025-08-18',
    scheduledTime: '10:00 ص - 12:00 م',
    status: 'completed',
    paymentMethod: 'cash',
    paymentStatus: 'paid',
    totalPrice: 180,
    createdAt: '2025-08-17T14:30:00Z',
    completedAt: '2025-08-18T11:45:00Z',
    rating: 5,
    reviewComment: 'ما شاء الله تبارك الله، فني ممتاز وأمين جداً، كشف المشكلة بدقة وتم الإصلاح فوراً بدون أي تكسير.',
  },
  {
    id: 'book_103',
    bookingNumber: 'KD-2025-083',
    customerId: 'user_cust_2',
    customerName: 'سارة خالد الدوسري',
    customerPhone: '0509876543',
    customerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    technicianId: 'user_tech_3',
    technicianName: 'م. سامر النجار - تكييف وتبريد',
    technicianPhone: '0558877665',
    technicianAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    specialtyId: 'cat_ac',
    specialtyName: 'تكييف وتبريد',
    serviceItems: ['غسيل وتنظيف مكيف سبليت مع جراب الحماية', 'تعبئة فريون هندي/أمريكي R410 و R22'],
    problemDescription: 'المكيف يخرج هواء دافئ ولا يبرد إطلاقاً وصوت المروحة مرتفع.',
    problemImages: [],
    location: {
      lat: 21.5794,
      lng: 39.1607,
      city: 'جدة',
      district: 'حي الروضة',
      addressText: 'شارع الأمير سلطان، الروضة',
    },
    scheduledDate: '2025-08-21',
    scheduledTime: '02:00 م - 04:00 م',
    status: 'accepted',
    paymentMethod: 'bank_transfer',
    paymentStatus: 'pending_verification',
    totalPrice: 249,
    createdAt: '2025-08-19T11:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    bookingId: 'book_102',
    technicianId: 'user_tech_2',
    customerId: 'user_cust_1',
    customerName: 'أحمد بن عبد الرحمن المنصوري',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'ما شاء الله تبارك الله، فني ممتاز وأمين جداً، كشف المشكلة بدقة وتم الإصلاح فوراً بدون أي تكسير وسعره جداً عادل.',
    createdAt: '2025-08-18T12:00:00Z',
  },
  {
    id: 'rev_2',
    bookingId: 'book_99',
    technicianId: 'user_tech_1',
    customerId: 'user_cust_2',
    customerName: 'سارة خالد الدوسري',
    customerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'المهندس طارق قمة في الاحترافية والأخلاق، جاء في الموعد بالضبط وقام بتركيب ثريات الصالة بإتقان فائق ونظف المكان بعد الانتهاء.',
    createdAt: '2025-08-10T16:20:00Z',
  },
  {
    id: 'rev_3',
    bookingId: 'book_98',
    technicianId: 'user_tech_3',
    customerId: 'user_cust_1',
    customerName: 'فهد المطيري',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'خدمة غسيل وتعبئة فريون ممتازة، المكيف رجع كأنه جديد وتبريده مثل الثلج. أنصح بالتعامل معه.',
    createdAt: '2025-08-05T18:00:00Z',
  },
];

export const INITIAL_CONVERSATIONS: ChatConversation[] = [
  {
    id: 'conv_1',
    bookingId: 'book_101',
    customerId: 'user_cust_1',
    customerName: 'أحمد بن عبد الرحمن المنصوري',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    technicianId: 'user_tech_1',
    technicianName: 'م. طارق الخالدي',
    technicianAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    lastMessage: 'أهلاً بك أخي أحمد، أنا في الطريق إليك الآن وسأصل بعد حوالي 15 دقيقة إن شاء الله.',
    lastMessageTime: '2025-08-19T12:20:00Z',
    unreadCountCustomer: 1,
    unreadCountTechnician: 0,
    messages: [
      {
        id: 'm1',
        senderId: 'user_cust_1',
        senderName: 'أحمد المنصوري',
        senderRole: 'customer',
        text: 'السلام عليكم يا مهندس طارق، هل معك مفكات فحص القواطع الذكية؟',
        timestamp: '2025-08-19T11:30:00Z',
        read: true,
      },
      {
        id: 'm2',
        senderId: 'user_tech_1',
        senderName: 'م. طارق الخالدي',
        senderRole: 'technician',
        text: 'وعليكم السلام ورحمة الله وبركاته، نعم يا غالي، جميع الأجهزة الرقمية ومقاييس الأحمال معي في السيارة.',
        timestamp: '2025-08-19T11:35:00Z',
        read: true,
      },
      {
        id: 'm3',
        senderId: 'user_tech_1',
        senderName: 'م. طارق الخالدي',
        senderRole: 'technician',
        text: 'أهلاً بك أخي أحمد، أنا في الطريق إليك الآن وسأصل بعد حوالي 15 دقيقة إن شاء الله.',
        timestamp: '2025-08-19T12:20:00Z',
        read: false,
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    userId: 'user_cust_1',
    title: 'الفني في الطريق إليك! 🚗',
    body: 'انطلق م. طارق الخالدي إلى موقعك لتقديم خدمة (كهرباء وإنارة) للطلب KD-2025-081.',
    type: 'booking',
    read: false,
    createdAt: '2025-08-19T12:15:00Z',
    linkId: 'book_101',
  },
  {
    id: 'notif_2',
    userId: 'user_cust_1',
    title: 'عرض خاص: خصم 25% على غسيل المكيفات ❄️',
    body: 'استعد لموسم الصيف مع باقة تنظيف 3 مكيفات وأكثر بأسعار حصرية واستخدم كود SUMMER25.',
    type: 'offer',
    read: true,
    createdAt: '2025-08-18T09:00:00Z',
  },
  {
    id: 'notif_3',
    userId: 'user_tech_1',
    title: 'طلب خدمة جديد رقم KD-2025-081 🔔',
    body: 'لديك طلب صيانة كهرباء جديد من العميل أحمد المنصوري بحي الملقا.',
    type: 'booking',
    read: true,
    createdAt: '2025-08-19T09:15:00Z',
    linkId: 'book_101',
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'comp_1',
    complaintNumber: 'CMP-2025-014',
    bookingId: 'book_95',
    customerId: 'user_cust_2',
    customerName: 'سارة خالد الدوسري',
    customerPhone: '0509876543',
    problemType: 'تأخر الفني عن الموعد المحدد',
    description: 'تم حجز موعد الساعة 4 عصراً والفني حضر الساعة 6:30 مساءً دون إشعار مسبق.',
    images: [],
    status: 'resolved',
    createdAt: '2025-08-12T19:00:00Z',
    resolutionNotes: 'تم التواصل مع العميل والاعتذار وتقديم كوبون خصم بقيمة 50 ريال وتنبيه الفني.',
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'off_1',
    title: 'عرض الصيف: خصم 25% على صيانة وغسيل المكيفات',
    description: 'غسيل عميق وضغط هواء مع تعبئة فريون أصلي لكافة أنواع المكيفات المنزلية.',
    discountPercent: 25,
    serviceCategoryId: 'cat_ac',
    serviceCategoryName: 'تكييف وتبريد',
    code: 'SUMMER25',
    validUntil: '2025-09-30',
    bannerImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop&q=80',
    active: true,
  },
  {
    id: 'off_2',
    title: 'فحص سباكة شامل وكشف تسربات مجاناً مع أي طلب صيانة',
    description: 'احصل على فحص دقيق لشبكة المياه وضغط المواسير عند طلب أي خدمة سباكة هذا الأسبوع.',
    discountPercent: 20,
    serviceCategoryId: 'cat_plumbing',
    serviceCategoryName: 'سباكة وصحية',
    code: 'PLUMB20',
    validUntil: '2025-08-31',
    bannerImage: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&auto=format&fit=crop&q=80',
    active: true,
  },
  {
    id: 'off_3',
    title: 'باقة النظافة الذهبية للفلل والشقق الجديدة',
    description: 'تنظيف عميق، جلي أرضيات، وتعقيم دورات المياه والمطابخ بأسعار تنافسية وضمان 100%.',
    discountPercent: 30,
    serviceCategoryId: 'cat_cleaning',
    serviceCategoryName: 'تنظيف وتعقيم',
    code: 'CLEAN30',
    validUntil: '2025-10-15',
    bannerImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    active: true,
  },
];
